name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2' # Updated Ruby version
          bundler-cache: true    # Automatically caches installed gems
          cache-version: 1       # Incremented cache version to ensure cache updates

      - name: Build with Jekyll
        run: bundle exec jekyll build
